### ISSUE TITLE
[FEATURE] Prevent consecutive Buys/Sells in GB and TV Indicator

### ISSUE THREAD

**Issue by cryptokoala4** [quantatrading/Quanta-exoTrader#15]
<img width="384" alt="image" src="https://github.com/quantatrading/Quanta-exoTrader/assets/13989105/8fb4c04d-5c4f-42a7-ac0b-28c022e17041">
Feature already exists, but can be exposed

Requesting this option for ExoTrader and TV Indicator for backtesting

Expected behaviour:
Two configurable options to set the number of candlesticks to wait until a new trade can be opened (Buy or Sell)

**Comment by quantatrading** [comment]
Thanks @cryptokoala4 

For notes splitting into 2 sub tasks:

1. GB algorithm - expose order time out multiplier to gui config using standard 2 * period but allowing user to specify the multiplier if required
2. TV indicator - design method to time out trades on order fill. Additional complexity with order types and backtesting assumptions

**Comment by quantatrading** [comment]
First stage able to derive epoch of math.max opened or closed trade



![Image](https://github.com/quantatrading/Quanta-exoTrader/assets/3750100/d039087f-f55b-4a0d-a740-acbdd7e59d2f)

**Comment by quantatrading** [comment]
TV Completed - leaving open and moving to in progress as GB exo needs refactor to expose conditions

- gui config code needs to be update
- core code needs updating with sanity checks
- wiki documentation needs updating to reflect the available setting

**Comment by quantatrading** [comment]
![Image](https://github.com/quantatrading/Quanta-exoTrader/assets/3750100/52e1209d-0743-41ba-a57a-aa0b21eff964)

Completed on GB exoTrader, moving to testing

**Comment by quantatrading** [comment]
Updating wiki documentation

**Comment by quantatrading** [comment]
Wiki documentation complete

**Comment by quantatrading** [comment]
Note: remove **available version** on release of v1.5

**Comment by quantatrading** [comment]
custom gui code complete and awaiting test end before pushing to GB

**Comment by quantatrading** [comment]
Promoting testing into live environment
