### ISSUE TITLE
[BUG] Potential issue in order centre - investigation required 

### ISSUE THREAD

**Issue by quantatrading** [quantatrading/Quanta-exoTrader#32]
**Describe the bug**
Looks like order centre reporting is off but user said trade purchased a significant amount more than TL allows.

What's not clear is that exchange return shows a different amount. Investigation

**Related to TV or exoTrader**
exoTrader

**To Reproduce**
Original volume: 1601
Original price: 0.0000215401
Buy Order Opts: { pair: 'SHIBUSDT', type: 'BUY', amount: 1601 }
retCode: 0,
'OK'
retExtInfo: {},
time: 1713491105991
result: { orderId: 1667278672117199872', orderLinkId: 17134911059811813' }.
607 {"retCode" :0, "retMsg": "OK"
', "result" :{"orderId":"1667278672117199872", "orderLinkId":"17134911059811813"}, "retExtInfo":(), "time" :1713491105991}

New buy rate 0.0000215199
is higher than current price of 0.0000215028,
adjusting rate
to
1.344e-7
• [32mPosting
SHIB buy market order for USDT-SHIB on bybit. Posting rate is: 1.344e-7. Posting amount is: 74404761.9

**Please ensure any attached document contains no personal protected information**

**Comment by quantatrading** [comment]
Refactored order centre call to orderProposal buy and sell and removed deprecated orderProposal code. No clear lineage that this caused any issue but good practice. Pushing code into live testing and awaiting users exchange confirmation on the buy (only seen TG output)

**Comment by DanielexoTrader** [comment]
The positions were also executed on ByBit. It comes to about 1600 in total.

![IMG_7276](https://github.com/quantatrading/Quanta-exoTrader/assets/167545253/04ff05ef-3a94-4826-af99-ad604faece7c)
![IMG_7274](https://github.com/quantatrading/Quanta-exoTrader/assets/167545253/709af311-15a7-4b38-bffa-396d458e6bd6)
![IMG_7275](https://github.com/quantatrading/Quanta-exoTrader/assets/167545253/e18fa2c4-563a-4830-92ec-5352da6af609)

**Comment by quantatrading** [comment]
Please keep an eye on announcements channel

**Comment by DanielexoTrader** [comment]
Hi Dave, the new version has been running for about 6 hours now. So far, all buys are in order. If something happens again that is not in line with the trading limit, I'll write to you.

**Comment by quantatrading** [comment]
Let's keep this ticket open until you are satisfied you don't see such a critical condition again. Thanks for updating and feeding back.

**Comment by quantatrading** [comment]
Checking in on you, any issues since patch?

**Comment by quantatrading** [comment]
@DanielexoTrader checking - has this issue been observed since patched?

**Comment by danielsappel** [comment]
Yes, since the patch everything has been working normally. I haven't seen it happen again where there were any unusual trading limits in the app. Thanks for your support.

**Comment by quantatrading** [comment]
Thank you @danielsappel - closing the issue
