### ISSUE TITLE
[FEATURE] Make TV sell orders have different labels depending on the sell type

### ISSUE THREAD

**Issue by mrgoogle** [quantatrading/Quanta-exoTrader#43]
**Describe the feature you are requesting and how it would benefit the performance or user flow**
Currently, we have 3 types of sell orders: normal sell, partial sell, and full sell. Since they currently have the same labels in TV strategy - "Close entry(s) order buy" - it is impossible to visually discern them on the chart without looking into the sell amounts (which also clutters the chart). It is especially relevant for the zoomed-out charts. Please, consider making those different.

**Is the request for TV or exoTrader?**
TradingView

**Have you considered achieving the outcome with current features?**
Yes, couldn't come up with any other solution other than straining my eyes even harder

**Provide examples or data to support the request**
![image](https://github.com/quantatrading/Quanta-exoTrader/assets/1553054/497ce912-5153-4d2e-9cb4-0e5250485e3a)

**Comment by quantatrading** [comment]
![Image](https://github.com/quantatrading/Quanta-exoTrader/assets/3750100/099e5bd7-d10c-44c0-8364-e2eb66690907)

Complete, build is now available
