### ISSUE TITLE
[FEATURE] Expose Max Buys and Total Profit to TV Data Window

### ISSUE THREAD

**Issue by mrgoogle** [quantatrading/Quanta-exoTrader#47]
**Describe the feature you are requesting and how it would benefit the performance or user flow**
Make "Max Buys" metric available in TV data window, so that this data could be used in optimization

**Is the request for TV or exoTrader?**
TradingView

**Comment by mrgoogle** [comment]
Ok, just saw you mentioning that TV PNL is inaccurate. Then please add Total Profit as well.

**Comment by cryptokoala4** [comment]
<img width="317" alt="image" src="https://github.com/quantatrading/Quanta-exoTrader/assets/13989105/e2890ea9-ec45-4dfe-adc1-0e162b5775b8">
Please expose these numbers so we can automate the backtesting data with third party tools

**Comment by quantatrading** [comment]
Updated and pushed live
