### ISSUE TITLE
[DOCUMENTATION] Update link in Getting Started section

### ISSUE THREAD

**Issue by BeerK0in** [quantatrading/Quanta-exoTrader#67]
**Is your request related to a problem with or missing documentation?**
Wrong link in existing documentation

**Is this related to TV or exoTrader?**
exoTrader

**Describe the documentation issue or request**
Visit https://github.com/quantatrading/Quanta-exoTrader/wiki/Getting-Started#setting-up-exotrader

The link in `4. Configure exoTrader: Configure your [trading parameters](https://github.com/quantatrading/Quanta-exoTrader/wiki/4.-Configuration#quanta-exotrader-configuration-settings).` is outdated

**Provide a link to the current documentation**
https://github.com/quantatrading/Quanta-exoTrader/wiki/Getting-Started#setting-up-exotrader

**Comment by quantatrading** [comment]
Thank you @BeerK0in
